<?xml version="1.0"?>
<!-- xacro ~/pisaBot/src/localization/urdf/bot.xacro > ~/pisaBot/src/localization/urdf/bot.xml && roslaunch logger visualize_bot.launch -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="pisaBot">
    <xacro:property name="wheel_diameter" value="0.065" />
    <xacro:property name="wheel_to_wheel_distance" value="0.123" /> 
    <xacro:property name="back_thickness" value="0.00625" /> 
    <xacro:property name="rad_per_deg" value="${pi/180}" /> 

    <xacro:property name="mpu_roll" value="2.9" />
    <xacro:property name="mpu_pitch" value="0.6" />
    <xacro:property name="mpu_yaw" value="-1.0" />
    <xacro:macro name="material">
        <material name="Grey">
            <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
    </xacro:macro>

    <link name="body">
        <visual>
            <origin xyz="${back_thickness/2 - 0.037} 0 ${0.15-0.006}" rpy="0 0 0" />
            <geometry>
                <box size="${back_thickness} 0.08 0.3" />
            </geometry>
            <xacro:material/>
        </visual>
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <box size="0.042 0.042 0.08" />
            </geometry>
            <xacro:material/>
        </visual>
        <visual>
            <origin xyz="0 ${wheel_to_wheel_distance/2} 0" rpy="${pi/2} 0 0" />
            <geometry>
                <cylinder length="0.027" radius="${wheel_diameter/2}"/>
            </geometry>
            <xacro:material/>
        </visual>
        <visual>
            <origin xyz="0 ${-wheel_to_wheel_distance/2} 0" rpy="${-pi/2} 0 0" />
            <geometry>
                <cylinder length="0.027" radius="${wheel_diameter/2}"/>
            </geometry>
            <xacro:material/>
        </visual>
    </link>

    <link name="mpu"/>
    <link name="ideal_mpu"/>

    <joint name="body_to_ideal_mpu" type="fixed">
        <parent link="body" />
        <child link="ideal_mpu" />
        <origin
            xyz="${back_thickness/2 - 0.037 + 0.0375 - 0.002} 0.01 0.157"
            rpy="${0} ${pi/2} ${pi}" />
    </joint>
    <!-- 0.157 m above the center
    0.002286 m off center
    37.5 cm in front of the back, the board is 1.5 mm thick -->

    <joint name="ideal_mpu_to_mpu" type="fixed">
        <parent link="ideal_mpu" />
        <child link="mpu" />
        <origin
            xyz="0 0 0"
            rpy="${mpu_roll * rad_per_deg} ${mpu_pitch * rad_per_deg} ${mpu_yaw * rad_per_deg}" />
    </joint>
</robot>